# Theme Settings
remote_theme : "mmistakes/minimal-mistakes"

# Site Settings
locale                   : "en-US"
title                    : "Faiz Khuzaimah"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Your Name"
description              : "An amazing website."
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "efemkay/efemkay.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/efemkay_logo.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

include: ["_pages"]

# Set the defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
